name: Generate Exports

on:
  push:
    branches:
      - master
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - run: |
        java gen/GenerateImport.java < README.md > following.csv
    - uses: pyTooling/Actions/releaser@v0.4.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-exports
        files: following.csv